In [1]:
import os, json, time
from pathlib import Path
from urllib.request import urlopen
from urllib.error import URLError, HTTPError
import numpy as np
import pandas as pd

In [4]:
import os
from pathlib import Path

if Path.cwd().name == 'notebooks':
    PROJECT_ROOT = Path('..')
else:
    PROJECT_ROOT = Path('.')

ENV_PATH = PROJECT_ROOT / '.env'
print(f"탐색 중인 .env 경로: {ENV_PATH.resolve()}")

def load_env(path: Path) -> dict:
    env = {}
    if not path.exists():
        print(".env 파일을 찾을 수 없습니다!")
        return env
    for line in path.read_text(encoding='utf-8-sig').splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        k, v = line.split('=', 1)
        v = v.strip().strip('"').strip("'")
        env[k.strip()] = v
    return env

env_vars = load_env(ENV_PATH)
SEOUL_API_KEY = env_vars.get('SEOUL_API_KEY', '')

# 4. 결과 확인
if SEOUL_API_KEY:
    print(f"API 키 로드 완료: {SEOUL_API_KEY[:6]}...")
else:
    print("API 키를 찾을 수 없습니다. .env 파일 안에 'SEOUL_API_KEY=값' 형태로 들어있는지 확인해주세요.")

# 디렉토리 세팅 (기존과 동일)
RAW_DIR = PROJECT_ROOT / 'data' / 'raw'
EXT_DIR = PROJECT_ROOT / 'data' / 'external'
RAW_DIR.mkdir(parents=True, exist_ok=True)
EXT_DIR.mkdir(parents=True, exist_ok=True)

BASE_URL = 'http://openapi.seoul.go.kr:8088'
QUARTERS = [f'{y}{q}' for y in range(2020, 2026) for q in range(1, 5)]
QUARTERS.append('20261')

탐색 중인 .env 경로: D:\2026\DM\2026-1_DM_final\.env
API 키 로드 완료: 414f43...

In [5]:
def fetch_one_page(endpoint, start, end, extra=''):
    suffix = f'/{extra}' if extra else ''
    url = f'{BASE_URL}/{SEOUL_API_KEY}/json/{endpoint}/{start}/{end}{suffix}'
    for attempt in range(3):
        try:
            with urlopen(url, timeout=30) as resp:
                payload = json.loads(resp.read().decode('utf-8'))
            block = payload.get(endpoint, {})
            result = block.get('RESULT', {})
            if result and result.get('CODE') not in ('INFO-000', None):
                return []
            return block.get('row', [])
        except (URLError, HTTPError, json.JSONDecodeError) as e:
            if attempt == 2:
                print(f'호출 실패 ({endpoint}, {extra}): {e}')
                return []
            time.sleep(1.5)
    return []

def fetch_all(endpoint, extra='', max_rows=50000):
    rows = []
    for start in range(1, max_rows + 1, 1000):
        end = start + 999
        page = fetch_one_page(endpoint, start, end, extra)
        if not page:
            break
        rows.extend(page)
        if len(page) < 1000:
            break
    return rows

In [4]:
# 매핑 파일 수집
MAPPING_PATH = RAW_DIR / 'TbgisTrdarRelm.csv'

if MAPPING_PATH.exists():
    df_map = pd.read_csv(MAPPING_PATH, dtype=str)
    print(f'캐시 사용: {len(df_map)}건')
else:
    rows = fetch_all('TbgisTrdarRelm', max_rows=2000)
    df_map = pd.DataFrame(rows)
    df_map.to_csv(MAPPING_PATH, index=False, encoding='utf-8-sig')
    print(f'수집 완료: {len(df_map)}건')

print(sorted(df_map['SIGNGU_CD_NM'].unique()))

수집 완료: 1650건
['강남구', '강동구', '강북구', '강서구', '관악구', '광진구', '구로구', '금천구', '노원구', '도봉구', '동대문구', '동작구', '마포구', '서대문구', '서초구', '성동구', '성북구', '송파구', '양천구', '영등포구', '용산구', '은평구', '종로구', '중구', '중랑구']

In [10]:
test_quarters = ['20231', '20232', '20233']
for q in test_quarters:
    rows = fetch_all('VwsmAdstrdSelngW', extra=q, max_rows=1000)
    df_test = pd.DataFrame(rows)
    if not df_test.empty and 'STDR_YYQU_CD' in df_test.columns:
        print(f'{q} → 실제 분기값: {df_test["STDR_YYQU_CD"].unique()}')
    else:
        print(f'{q} → 빈 응답')

20231 → 실제 분기값: <StringArray>
['20231']
Length: 1, dtype: str
20232 → 실제 분기값: <StringArray>
['20232']
Length: 1, dtype: str
20233 → 실제 분기값: <StringArray>
['20233']
Length: 1, dtype: str

In [11]:
print("VwsmAdstrdSelngW 행정동·업종·분기 매출 수집")
frames = []
for q in QUARTERS:
    rows = fetch_all('VwsmAdstrdSelngW', extra=q, max_rows=50000)
    if rows:
        df = pd.DataFrame(rows)
        df['q'] = q
        frames.append(df)
        print(f'{q}: {len(df)}행')
    else:
        print(f'{q}: 빈 응답')

df_sales = pd.concat(frames, ignore_index=True)
print(f'\n총 수집 행수: {len(df_sales)}')
print(f'컬럼: {list(df_sales.columns)[:10]}')

VwsmAdstrdSelngW 행정동·업종·분기 매출 수집
20201: 16502행
20202: 16648행
20203: 16676행
20204: 16675행
20211: 17536행
20212: 17541행
20213: 17514행
20214: 17480행
20221: 17394행
20222: 17401행
20223: 17346행
20224: 17299행
20231: 17188행
20232: 17196행
20233: 17137행
20234: 17122행
20241: 17044행
20242: 17048행
20243: 16937행
20244: 16871행
20251: 16770행
20252: 16794행
20253: 16831행
20254: 16718행
20261: 빈 응답

총 수집 행수: 409668
컬럼: ['STDR_YYQU_CD', 'ADSTRD_CD', 'ADSTRD_CD_NM', 'SVC_INDUTY_CD', 'SVC_INDUTY_CD_NM', 'THSMON_SELNG_AMT', 'THSMON_SELNG_CO', 'MDWK_SELNG_AMT', 'WKEND_SELNG_AMT', 'MON_SELNG_AMT']

In [12]:
print("VwsmAdstrdFlpopW 행정동·분기 유동인구 수집")
frames = []
for q in QUARTERS:
    rows = fetch_all('VwsmAdstrdFlpopW', extra=q, max_rows=50000)
    if rows:
        df = pd.DataFrame(rows)
        df['q'] = q
        frames.append(df)
        print(f'{q}: {len(df)}행')
    else:
        print(f'{q}: 빈 응답')

df_flpop = pd.concat(frames, ignore_index=True)
print(f'\n총 수집 행수: {len(df_flpop)}')
print(f'컬럼: {list(df_flpop.columns)[:10]}')

VwsmAdstrdFlpopW 행정동·분기 유동인구 수집
20201: 11900행
20202: 11900행
20203: 11900행
20204: 11900행
20211: 11900행
20212: 11900행
20213: 11900행
20214: 11900행
20221: 11900행
20222: 11900행
20223: 11900행
20224: 11900행
20231: 11900행
20232: 11900행
20233: 11900행
20234: 11900행
20241: 11900행
20242: 11900행
20243: 11900행
20244: 11900행
20251: 11900행
20252: 11900행
20253: 11900행
20254: 11900행
20261: 11900행

총 수집 행수: 297500
컬럼: ['STDR_YYQU_CD', 'ADSTRD_CD', 'ADSTRD_CD_NM', 'TOT_FLPOP_CO', 'ML_FLPOP_CO', 'FML_FLPOP_CO', 'AGRDE_10_FLPOP_CO', 'AGRDE_20_FLPOP_CO', 'AGRDE_30_FLPOP_CO', 'AGRDE_40_FLPOP_CO']

→ 3.2 유동인구 분기 필터 무시 확인, 정적 처리 예정

In [13]:
print("VwsmAdstrdStorW 행정동·업종·분기 점포수 수집")
frames = []
for q in QUARTERS:
    rows = fetch_all('VwsmAdstrdStorW', extra=q, max_rows=50000)
    if rows:
        df = pd.DataFrame(rows)
        df['q'] = q
        frames.append(df)
        print(f'{q}: {len(df)}행')
    else:
        print(f'{q}: 빈 응답')

df_stor = pd.concat(frames, ignore_index=True)
print(f'\n총 수집 행수: {len(df_stor)}')
print(f'컬럼: {list(df_stor.columns)[:10]}')

VwsmAdstrdStorW 행정동·업종·분기 점포수 수집
20201: 34938행
20202: 34975행
20203: 36584행
20204: 35114행
20211: 35105행
20212: 35088행
20213: 35081행
20214: 35121행
20221: 35124행
20222: 35129행
20223: 35160행
20224: 35208행
20231: 35261행
20232: 35282행
20233: 35331행
20234: 35361행
20241: 35330행
20242: 35267행
20243: 35207행
20244: 35197행
20251: 35281행
20252: 35294행
20253: 35326행
20254: 35317행
20261: 빈 응답

총 수집 행수: 846081
컬럼: ['STDR_YYQU_CD', 'ADSTRD_CD', 'ADSTRD_CD_NM', 'SVC_INDUTY_CD', 'SVC_INDUTY_CD_NM', 'STOR_CO', 'SIMILR_INDUTY_STOR_CO', 'OPBIZ_RT', 'OPBIZ_STOR_CO', 'CLSBIZ_RT']

In [ ]:
# 중간 산출물 저장 
df_sales.to_csv(RAW_DIR / 'team3_adstrd_selng.csv', encoding='utf-8-sig', index=False)
print(f'3.1 매출 저장 완료: {len(df_sales)}행')

df_flpop.to_csv(RAW_DIR / 'team3_adstrd_flpop.csv', encoding='utf-8-sig', index=False)
print(f'3.2 유동인구 저장 완료: {len(df_flpop)}행')

df_stor.to_csv(RAW_DIR / 'team3_adstrd_stor.csv', encoding='utf-8-sig', index=False)
print(f'3.3 점포수 저장 완료: {len(df_stor)}행')

3.1 매출 저장 완료: 409668행
3.2 유동인구 저장 완료: 297500행
3.3 점포수 저장 완료: 846081행

In [ ]:
test_apis = {
    '3.4 직장인구': 'VwsmAdstrdWrcPopltnW',
    '3.5 집객시설': 'VwsmAdstrdFcltyW',
    '3.6 변화지표': 'VwsmAdstrdIxQq'
}
test_quarters = ['20201', '20202', '20203']

for name, endpoint in test_apis.items():
    print(f"\n [{name}] 분기 필터 작동 검증 ({endpoint})")
    print("-" * 50)
    
    for q in test_quarters:
        # 1000행(1페이지)만 호출해서 응답 확인
        rows = fetch_all(endpoint, extra=q, max_rows=1000)
        df_test = pd.DataFrame(rows)
        
        if not df_test.empty and 'STDR_YYQU_CD' in df_test.columns:
            actual_q = df_test["STDR_YYQU_CD"].unique()
            print(f"요청: {q} 분기 응답 행수: {len(df_test)}행 | 실제 데이터 분기값: {actual_q}")
        else:
            print(f"요청: {q} 분기 데이터가 비어있거나 'STDR_YYQU_CD' 컬럼이 없습니다.")

 [3.4 직장인구] 분기 필터 작동 검증 (VwsmAdstrdWrcPopltnW)
--------------------------------------------------
요청: 20201 분기 응답 행수: 414행 | 실제 데이터 분기값: <StringArray>
['20201']
Length: 1, dtype: str
요청: 20202 분기 응답 행수: 414행 | 실제 데이터 분기값: <StringArray>
['20202']
Length: 1, dtype: str
요청: 20203 분기 응답 행수: 414행 | 실제 데이터 분기값: <StringArray>
['20203']
Length: 1, dtype: str

 [3.5 집객시설] 분기 필터 작동 검증 (VwsmAdstrdFcltyW)
--------------------------------------------------
요청: 20201 분기 응답 행수: 1000행 | 실제 데이터 분기값: <StringArray>
['20204', '20211', '20212', '20213', '20214', '20221', '20222', '20223',
 '20224', '20234', '20231', '20232', '20233', '20244', '20242', '20243',
 '20241', '20252', '20253']
Length: 19, dtype: str
요청: 20202 분기 응답 행수: 1000행 | 실제 데이터 분기값: <StringArray>
['20204', '20211', '20212', '20213', '20214', '20221', '20222', '20223',
 '20224', '20234', '20231', '20232', '20233', '20244', '20242', '20243',
 '20241', '20252', '20253']
Length: 19, dtype: str
요청: 20203 분기 응답 행수: 1000행 | 실제 데이터 분기값: <StringArray>
['20204', '20211', '20212', '20213', '20214', '20221', '20222', '20223',
 '20224', '20234', '20231', '20232', '20233', '20244', '20242', '20243',
 '20241', '20252', '20253']
Length: 19, dtype: str

 [3.6 변화지표] 분기 필터 작동 검증 (VwsmAdstrdIxQq)
--------------------------------------------------
요청: 20201 분기 응답 행수: 1000행 | 실제 데이터 분기값: <StringArray>
['20254', '20242', '20243', '20241', '20244', '20191', '20252', '20192',
 '20193', '20194', '20201', '20202', '20203', '20214', '20221', '20234',
 '20204', '20211', '20212', '20213', '20222', '20223', '20233', '20231',
 '20232', '20224']
Length: 26, dtype: str
요청: 20202 분기 응답 행수: 1000행 | 실제 데이터 분기값: <StringArray>
['20254', '20242', '20243', '20241', '20244', '20191', '20252', '20192',
 '20193', '20194', '20201', '20202', '20203', '20214', '20221', '20234',
 '20204', '20211', '20212', '20213', '20222', '20223', '20233', '20231',
 '20232', '20224']
Length: 26, dtype: str
요청: 20203 분기 응답 행수: 1000행 | 실제 데이터 분기값: <StringArray>
['20254', '20242', '20243', '20241', '20244', '20191', '20252', '20192',
 '20193', '20194', '20201', '20202', '20203', '20214', '20221', '20234',
 '20204', '20211', '20212', '20213', '20222', '20223', '20233', '20231',
 '20232', '20224']
Length: 26, dtype: str

→ 3.5 집객시설 & 3.6 변화지표 분기 필터 무시 확인, 정적 처리 예정

In [9]:
print("VwsmAdstrdWrcPopltnW 행정동·분기 직장인구 수집")
frames = []
for q in QUARTERS:
    rows = fetch_all('VwsmAdstrdWrcPopltnW', extra=q, max_rows=50000)
    if rows:
        df = pd.DataFrame(rows)
        df['q'] = q
        frames.append(df)
        print(f'{q}: {len(df)}행')
    else:
        print(f'{q}: 빈 응답')

df_wrc = pd.concat(frames, ignore_index=True)
print(f'\n총 수집 행수: {len(df_wrc)}')
print(f'컬럼: {list(df_wrc.columns)[:10]}')

df_wrc.to_csv(RAW_DIR / 'team3_adstrd_wrc_popltn.csv', encoding='utf-8-sig', index=False)
print(f'3.4 직장인구 저장 완료: {len(df_wrc)}행')

VwsmAdstrdWrcPopltnW 행정동·분기 직장인구 수집
20201: 414행
20202: 414행
20203: 414행
20204: 414행
20211: 414행
20212: 414행
20213: 414행
20214: 414행
20221: 414행
20222: 414행
20223: 414행
20224: 414행
20231: 414행
20232: 414행
20233: 414행
20234: 414행
20241: 414행
20242: 414행
20243: 414행
20244: 414행
20251: 414행
20252: 414행
20253: 414행
20254: 414행
20261: 빈 응답

총 수집 행수: 9936
컬럼: ['STDR_YYQU_CD', 'ADSTRD_CD', 'ADSTRD_CD_NM', 'TOT_WRC_POPLTN_CO', 'ML_WRC_POPLTN_CO', 'FML_WRC_POPLTN_CO', 'AGRDE_10_WRC_POPLTN_CO', 'AGRDE_20_WRC_POPLTN_CO', 'AGRDE_30_WRC_POPLTN_CO', 'AGRDE_40_WRC_POPLTN_CO']
3.4 직장인구 저장 완료: 9936행

In [10]:
print("VwsmAdstrdFcltyW 행정동·분기 집객시설 수집 및 정적 처리")
rows_fclty = fetch_all('VwsmAdstrdFcltyW', extra='20201', max_rows=50000)
df_fclty = pd.DataFrame(rows_fclty)

if not df_fclty.empty:
    # 가장 최신 분기 찾기
    latest_q_fclty = df_fclty['STDR_YYQU_CD'].max()
    print(f"[3.5 집객시설] 가장 최신 분기: {latest_q_fclty}")
    
    # 최신 분기 데이터만 필터링 및 중복 제거
    df_fclty_static = df_fclty[df_fclty['STDR_YYQU_CD'] == latest_q_fclty].copy()
    df_fclty_static = df_fclty_static.drop_duplicates(subset=['ADSTRD_CD'])
    
    print(f"[3.5 집객시설] 정제 후 남은 행 수: {len(df_fclty_static)}행")
    display(df_fclty_static.head(2))

VwsmAdstrdFcltyW 행정동·분기 집객시설 수집 및 정적 처리
[3.5 집객시설] 가장 최신 분기: 20254
[3.5 집객시설] 정제 후 남은 행 수: 425행

,STDR_YYQU_CD,ADSTRD_CD,ADSTRD_CD_NM,VIATR_FCLTY_CO,PBLOFC_CO,BANK_CO,GEHSPT_CO,GNRL_HSPTL_CO,PARMACY_CO,KNDRGR_CO,...,UNIV_CO,DRTS_CO,SUPMK_CO,THEAT_CO,STAYNG_FCLTY_CO,ARPRT_CO,RLROAD_STATN_CO,BUS_TRMINL_CO,SUBWAY_STATN_CO,BUS_STTN_CO
1103,20254,11440690,망원1동,95.0,2.0,2.0,0.0,0.0,11.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,23.0
7237,20254,11110515,청운효자동,93.0,6.0,3.0,0.0,0.0,4.0,1.0,...,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,26.0

In [11]:
print("VwsmAdstrdIxQq 행정동·분기 변화지표 수집 및 정적 처리")
rows_ix = fetch_all('VwsmAdstrdIxQq', extra='20201', max_rows=50000)
df_ix = pd.DataFrame(rows_ix)

if not df_ix.empty:
    # 가장 최신 분기 찾기
    latest_q_ix = df_ix['STDR_YYQU_CD'].max()
    print(f"[3.6 변화지표] 가장 최신 분기: {latest_q_ix}")
    
    # 최신 분기 데이터만 필터링 및 중복 제거
    df_ix_static = df_ix[df_ix['STDR_YYQU_CD'] == latest_q_ix].copy()
    df_ix_static = df_ix_static.drop_duplicates(subset=['ADSTRD_CD'])
    
    print(f"[3.6 변화지표] 정제 후 남은 행 수: {len(df_ix_static)}행")
    display(df_ix_static.head(2))

VwsmAdstrdIxQq 행정동·분기 변화지표 수집 및 정적 처리
[3.6 변화지표] 가장 최신 분기: 20254
[3.6 변화지표] 정제 후 남은 행 수: 425행

,STDR_YYQU_CD,ADSTRD_CD,ADSTRD_CD_NM,TRDAR_CHNGE_IX,TRDAR_CHNGE_IX_NM,OPR_SALE_MT_AVRG,CLS_SALE_MT_AVRG,SU_OPR_SALE_MT_AVRG,SU_CLS_SALE_MT_AVRG
0,20254,11140550,명동,HH,정체,128.0,59.0,115.0,53.0
1,20254,11350560,월계1동,LH,상권확장,111.0,54.0,115.0,53.0

In [12]:
if not df_fclty_static.empty:
    out_path_fclty = RAW_DIR / 'team3_adstrd_fclty_static.csv'
    df_fclty_static.to_csv(out_path_fclty, encoding='utf-8-sig', index=False)
    print(f"3.5 집객시설 저장 완료: {out_path_fclty.name}")

3.5 집객시설 저장 완료: team3_adstrd_fclty_static.csv

In [13]:
if not df_ix_static.empty:
    out_path_ix = RAW_DIR / 'team3_adstrd_ix_static.csv'
    df_ix_static.to_csv(out_path_ix, encoding='utf-8-sig', index=False)
    print(f"3.6 변화지표 저장 완료: {out_path_ix.name}")

3.6 변화지표 저장 완료: team3_adstrd_ix_static.csv

In [15]:
print("VwsmAdstrdFlpopW 유동인구 기존 데이터 정적 처리")

flpop_path = RAW_DIR / 'team3_adstrd_flpop.csv'
df_flpop = pd.read_csv(flpop_path)

if not df_flpop.empty:
    # 가장 최신 분기 찾기 (수집할 때 파생 변수로 만든 'q' 컬럼 기준)
    latest_q_flpop = df_flpop['q'].max()
    print(f"[3.2 유동인구] 가장 최신 분기: {latest_q_flpop}")
    
    # 최신 분기 데이터만 필터링
    df_flpop_static = df_flpop[df_flpop['q'] == latest_q_flpop].copy()
    
    # 행정동(ADSTRD_CD) 기준 중복 행 제거
    df_flpop_static = df_flpop_static.drop_duplicates(subset=['ADSTRD_CD'])
    
    print(f"[3.2 유동인구] 정제 후 남은 행 수: {len(df_flpop_static)}행")
    display(df_flpop_static.head(2))

VwsmAdstrdFlpopW 유동인구 기존 데이터 정적 처리
[3.2 유동인구] 가장 최신 분기: 20261
[3.2 유동인구] 정제 후 남은 행 수: 425행

,STDR_YYQU_CD,ADSTRD_CD,ADSTRD_CD_NM,TOT_FLPOP_CO,ML_FLPOP_CO,FML_FLPOP_CO,AGRDE_10_FLPOP_CO,AGRDE_20_FLPOP_CO,AGRDE_30_FLPOP_CO,AGRDE_40_FLPOP_CO,...,TMZON_17_21_FLPOP_CO,TMZON_21_24_FLPOP_CO,MON_FLPOP_CO,TUES_FLPOP_CO,WED_FLPOP_CO,THUR_FLPOP_CO,FRI_FLPOP_CO,SAT_FLPOP_CO,SUN_FLPOP_CO,q
285600,20251,11470650,신정4동,11161259.0,5298730.0,5862530.0,2014866.0,1550536.0,1684552.0,1822821.0,...,1801698.0,1460015.0,1583855.0,1580905.0,1583017.0,1583085.0,1586056.0,1624071.0,1620270.0,20261
285601,20251,11470670,신정6동,1948405.0,873582.0,1074823.0,562259.0,165991.0,203822.0,371528.0,...,325424.0,248078.0,278114.0,275763.0,276331.0,277853.0,279999.0,280472.0,279871.0,20261

In [16]:
if not df_flpop_static.empty:
    out_path_flpop = RAW_DIR / 'team3_adstrd_flpop_static.csv'
    df_flpop_static.to_csv(out_path_flpop, encoding='utf-8-sig', index=False)
    print(f"3.2 유동인구 정적 변수 저장 완료: {out_path_flpop.name}")

3.2 유동인구 정적 변수 저장 완료: team3_adstrd_flpop_static.csv